# Generated by Django 5.2.4 on 2025-07-25 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_choice_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='auteur',
        ),
        migrations.AlterField(
            model_name='choice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='choices/'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='texte',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='texte',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Texte'), ('image', 'Image')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.categorie'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
